# Generated by Django 5.2.4 on 2025-07-06 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='status',
            new_name='project_status',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='status',
            new_name='task_status',
        ),
    ]
