# Generated by Django 5.2.4 on 2025-07-06 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancevisit',
            name='assigned_technician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_maintenance_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='warrantyclaim',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_warranty_claims', to='crm.customer'),
        ),
    ]
