# Generated by Django 5.2.4 on 2025-07-06 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_maintenancevisit_assigned_technician_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='status',
            new_name='lead_status',
        ),
        migrations.RenameField(
            model_name='opportunity',
            old_name='status',
            new_name='opportunity_status',
        ),
        migrations.RenameField(
            model_name='warrantyclaim',
            old_name='status',
            new_name='warrantyclaim_status',
        ),
    ]
