# Generated by Django 5.2.4 on 2025-07-06 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('is_raw_material', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkstationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BOMComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='manufacturing.billofmaterials')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturing.item')),
            ],
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='manufacturing.item'),
        ),
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('planned_start_date', models.DateField()),
                ('planned_end_date', models.DateField()),
                ('productionplan_status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturing.item')),
            ],
        ),
        migrations.CreateModel(
            name='Routing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturing.item')),
            ],
        ),
        migrations.CreateModel(
            name='RoutingOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturing.operation')),
                ('routing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturing.routing')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('routing', 'operation')},
            },
        ),
        migrations.AddField(
            model_name='routing',
            name='operations',
            field=models.ManyToManyField(through='manufacturing.RoutingOperation', to='manufacturing.operation'),
        ),
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('entry_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out')], max_length=3)),
                ('date', models.DateField(auto_now_add=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturing.item')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('scheduled_start_date', models.DateField()),
                ('scheduled_end_date', models.DateField()),
                ('workorder_status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('STARTED', 'Started'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturing.item')),
                ('production_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='manufacturing.productionplan')),
            ],
        ),
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('jobcard_status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturing.operation')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_cards', to='manufacturing.workorder')),
                ('workstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturing.workstation')),
            ],
        ),
        migrations.CreateModel(
            name='DowntimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('workstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturing.workstation')),
            ],
        ),
        migrations.AddField(
            model_name='workstation',
            name='workstation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturing.workstationtype'),
        ),
        migrations.AddField(
            model_name='operation',
            name='workstation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturing.workstationtype'),
        ),
    ]
