# Generated by Django 5.2.4 on 2025-07-06 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SerialNumber',
            new_name='InventorySerialNumber',
        ),
    ]
