# Generated by Django 5.2.4 on 2025-07-06 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_contact_designation_customer_address_and_more'),
        ('sales', '0002_remove_contact_customer_remove_customer_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='sales_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.salesperson'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='sales_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.salesperson'),
        ),
        migrations.DeleteModel(
            name='SalesPerson',
        ),
    ]
