# Generated by Django 5.2.4 on 2025-07-06 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='status',
            new_name='issue_status',
        ),
        migrations.RenameField(
            model_name='warrantyclaim',
            old_name='status',
            new_name='warrantyclaim_status',
        ),
    ]
