# Generated by Django 5.2.4 on 2025-07-06 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_contact_designation_customer_address_and_more'),
        ('support', '0002_rename_status_issue_issue_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SerialNumber',
            new_name='SupportSerialNumber',
        ),
    ]
